# Generated by Django 4.2.11 on 2024-07-02 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_connection_connection_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="follower",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
