# Generated by Django 4.2.11 on 2024-07-14 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_connection_follower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="following",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
