# Generated by Django 4.2.11 on 2024-07-02 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0002_tweet_created_at_tweet_user_alter_tweet_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweet_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
