# Generated by Django 4.2.11 on 2024-09-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0007_favorite_favorite_favorite_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tweet_liked", to="tweets.tweet"
            ),
        ),
    ]
